<table cellspacing="0" style="width:550px; border: 3px solid #c9c9c9; font-family: Helvetica, Arial, sans-serif;">
    <tr height="120px" width="100%" style="background-color: #000;">
        <th style="text-align:right; font-size:1.2em; color: #FFFFFF; padding: 10px;">
            Wager Help
        </th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 10px;">
            <div style="margin:auto; width:90%;">
                <h1 style="font-weight: 400;font-size:1.5em;color:#d72027;">
                We've received your request!
                </h1>
                <div style="font-size:.9em;font-weight:200;">
                    <p><?php echo $this->userEmail;?>,</p>
                    <p style="margin:25px 0px">Thanks for reaching out! We have received your request and are working hard on getting back to you as soon as possible.
                    </p>
                    <p style="margin:10px 0px">You will receive our reply within the next 48 hours to your question: 
                    </p>
                    <p style="margin:10px 0px"><?php echo $this->helpQuestion;?></p>
                    <p style="margin:10px 0px">Thanks,</p>
                    <p style="margin:10px 0px"><i>The GamerWall Team</i></p>
                </div>
            </div>
        </td>
    </tr>
    <tr style="background-color: #000;">
        <th style="text-align:center; font-size:.75em;font-weight:100;  color: #FFFFFF; padding: 10px;">
            <p><i>Please note you are receiving this because you have requested Wager Support on your GamerWall account.</i></p>
        </th>
    </tr>
</table>
