<table cellspacing="0" style="width:550px; border: 3px solid #c9c9c9; font-family: Helvetica, Arial, sans-serif;">
    <tr height="120px" width="100%" style="background-color: #000;">
        <th style="text-align:right; font-size:1.2em; color: #FFFFFF; padding: 10px;">
            Wager Result
        </th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 10px;">
            <div style="margin:auto; width:90%;">
                <h1 style="font-weight: 400;font-size:1.5em;color:#d72027;">
                Confirm Wager Result
                </h1>
                <div style="font-size:.9em;font-weight:200;">
                    <p style="margin:25px 0px">Your opponent has confirmed their match result. 
                    </p>
                    <p style="margin:25px 0px">Wager: <?php echo $this->matchId . ': ' . $this->consoleName . ' - ' . $this->gameName;?>
                    </p>
                    <p style="margin:25px 0px">Opponent: <?php echo $this->username ;?>
                    </p>
                    <p style="margin:25px 0px">Wager Amount: <?php echo $this->riskAmount;?>
                    </p>
                     <p style="margin:25px 0px">Status: <?php echo $this->status;?>
                    </p>
                     <p style="margin:25px 0px">Please confirm your Wager Result.  
                    </p>
                </div>
            </div>
        </td>
    </tr>
    <tr style="background-color: #000;">
        <th style="text-align:center; font-size:.75em;font-weight:100;  color: #FFFFFF; padding: 10px;">
            <p><i>Please note you are receiving this because your Wager Results has Not yet been reported on your GamerWall account.</i></p>
        </th>
    </tr>
</table>