<?php
  echo $this->partial('wager/partials/topmenu.phtml');
  echo $this->partial('wager/partials/sidemenu.phtml');
  
  $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/backoffice/profile.css')
                   ->appendStylesheet($this->basePath() . '/css/plugins/datatables/datatables.css');
  
  $changeUsername->setAttribute('action', $this->url('wager', array('action' => 'index', 'controller' => 'profile')));
  $changeUsername->prepare();
  $changeUsernamePlaceholder = $changeUsername->get('username');
  $changeUsernamePlaceholder->setAttribute('placeholder', $this->username);
  
  //$changeCurrency->setAttribute('action', $this->url('wager', array('action' => 'index', 'controller' => 'profile')));
  //$changeCurrency->prepare();
  
  $changePassword->setAttribute('action', $this->url('wager', array('action' => 'index', 'controller' => 'profile')));
  $changePassword->prepare();
  $changeEmail->setAttribute('action', $this->url('wager', array('action' => 'index', 'controller' => 'profile')));
  $changeEmail->prepare();
  
  $changeEmailPlaceholder = $changeEmail->get('email');
  $changeEmailPlaceholder->setAttribute('placeholder', $this->userEmail);
  
  
  $consoleUsername->setAttribute('action', $this->url('wager', array('action' => 'index', 'controller' => 'profile')));
  $consoleUsername->prepare();
  
?>


<?php echo $this->partial('wager/partials/wager.phtml',  array('newwager' => $newwager))?>


<!-- begin MAIN PAGE CONTENT -->
<div id="page-wrapper">

    <div class="page-content">
    <!-- begin PAGE TITLE ROW -->
    <div class="row">
        <div class="col-lg-12">
            <div class="page-title removeLowerPageTitleMargin">
                <h1>
                    User Profile
                    <small>View your login history, update email and password settings</small>
                </h1>
                <ol class="breadcrumb">
                    <li><i class="fa fa-desktop"></i>  <a href="<?php echo $this->url('wager', array('action'=>'index', 'controller' => 'index'))?>">The Wager Wall</a>
                    </li>
                    <li class="active">User Profile</li>
                </ol>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- end PAGE TITLE ROW -->
    
    <div class="row">
        <div class="col-lg-12">
    
            <div class="portlet portlet-default portlet-white portlet-flat-top">
                <div class="portlet-body">
                    <ul id="userTab" class="nav nav-tabs">
                        <li class="active"><a href="#profile-settings" data-toggle="tab">Update Profile</a>
                        </li>
                        <li><a href="#overview" data-toggle="tab">Login History</a>
                        </li>
                    </ul>
                    <div id="userTabContent" class="tab-content">
                        <div class="tab-pane active fade in" id="profile-settings">
                            <div class="row">
                                <div class="col-sm-3">
                                    <ul id="userSettings" class="nav nav-pills nav-stacked">
                                        <li class="active"><a href="#username" data-toggle="tab"><i class="fa fa-user fa-fw"></i> Change Username</a>
                                        </li>
                                        <li><a  href="#console" data-toggle="tab"><i class="fa fa-usd fa-fw"></i> Add/Edit Console User Name</a>
                                        </li>
                                        <li><a href="#basicInformation" data-toggle="tab"><i class="fa fa-user fa-fw"></i> Account Email</a>
                                        </li>
                                        <li><a href="#changePassword" data-toggle="tab"><i class="fa fa-lock fa-fw"></i> Change Password</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-sm-9">
                                    <div id="userSettingsContent" class="tab-content">
                                        <div class="tab-pane fade in active" id="username">
                                            <?php  echo $this->form()->openTag($changeUsername);?>
                                                <h3>Change Account Username:</h3>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($changeUsername->get('username'));?>
                                                    <?php echo $this->formelementerrors($changeUsername->get('username'), array('class' => 'error_red'));?>
                                                </div>
                                                <input type="hidden" name="form_type" value="changeUsername"/>
                                                <?php echo $this->formElement($changeUsername->get('submit'));?>
                                                <button class="btn btn-red">Cancel</button>
                                            <?php echo $this->form()->closeTag();?>
                                        </div>
                                        <div class="tab-pane fade in" id="console">
                                            <?php  echo $this->form()->openTag($consoleUsername);?>
                                                <h3>Console Username:</h3>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($consoleUsername->get('xboxGamertag'));?>
                                                    <?php echo $this->formelementerrors($consoleUsername->get('xboxGamertag'), array('class' => 'error_red'));?>
                                                    
                                                    <?php echo $this->formElement($consoleUsername->get('pSNUsername'));?>
                                                    <?php echo $this->formelementerrors($consoleUsername->get('pSNUsername'), array('class' => 'error_red'));?>
                                                </div>
                                                <input type="hidden" name="form_type" value="consoleUsername"/>
                                                <?php echo $this->formElement($consoleUsername->get('submit'));?>
                                                <button class="btn btn-red">Cancel</button>
                                            <?php echo $this->form()->closeTag();?>
                                        </div>                                        
                                        
<!--                                        <div class="tab-pane fade in" id="currency">
                                            <?php // echo $this->form()->openTag($changeCurrency);?>
                                                <h3>Change Default Currency:</h3>
                                                <div class="form-group">
                                                    <?php //echo $this->formElement($changeCurrency->get('currency'));?>
                                                    <?php //echo $this->formelementerrors($changeCurrency->get('currency'), array('class' => 'error_red'));?>
                                                </div>
                                                <input type="hidden" name="form_type" value="changeCurrency"/>
                                                <?php //echo $this->formElement($changeCurrency->get('submit'));?>
                                                <button class="btn btn-red">Cancel</button>
                                            <?php //echo $this->form()->closeTag();?>
                                        </div>-->
                                        <div class="tab-pane fade" id="basicInformation">
                                            <?php  echo $this->form()->openTag($changeEmail);?>
                                                <h3>Change Account Email Address:</h3>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($changeEmail->get('email'));?>
                                                    <?php echo $this->formelementerrors($changeEmail->get('email'), array('class' => 'error_red'));?>
                                                </div>
                                                <input type="hidden" name="form_type" value="changeEmail"/>
                                                <?php echo $this->formElement($changeEmail->get('submit'));?>
                                                <button class="btn btn-red">Cancel</button>
                                                <p class="update_email_notice">Note: By updating your email address, you will be logged out until validation of your email is complete.</p>
                                            <?php echo $this->form()->closeTag();?>
                                        </div>
                                        <div class="tab-pane fade in" id="changePassword">
                                            <h3>Change Password:</h3>
                                            <?php  echo $this->form()->openTag($changePassword);?>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($changePassword->get('original_password'));?>
                                                    <?php echo $this->formelementerrors($changePassword->get('original_password'));?>
                                                </div>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($changePassword->get('password'));?>
                                                    <?php echo $this->formelementerrors($changePassword->get('password'), array('class' => 'error_red'));?>
                                                </div>
                                                <div class="form-group">
                                                    <?php echo $this->formElement($changePassword->get('repeat_password'));?>
                                                    <?php echo $this->formelementerrors($changePassword->get('repeat_password'));?>
                                                </div>
                                                <input type="hidden" name="form_type" value="changePassword"/>
                                                <?php echo $this->formElement($changePassword->get('submit'));?>
                                                <button class="btn btn-red">Cancel</button>
                                            <?php echo $this->form()->closeTag();?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-content fade" id="overview">
                          <div class="row">
                            <div class="col-sm-3">
                              <ul id="" class="nav nav-pills nav-stacked">
                                <li class="active"><a href="#loginHistory" data-toggle="tab">Login History</a></li>
                              </ul>
                            </div>
                            <div class="col-sm-9">
                              <div class="tab-content">
                                <div class="tab-pane fade in active" id="loginHistory">
                                  <h2><?php echo $this->userEmail;?></h2>
                                  <h3>Login History</h3>
                                  <div class="table-responsive">
                                    <table id="logins-table" class="table table-striped table-bordered table-hover table-red">
                                      <thead>
                                        <tr>
                                          <th>Date/Time (Times shown in UTC)</th>
                                          <th>IP Address</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                      <?php
                                        if($this->logins){
                                            foreach($this->logins as $login){
                                              echo '<tr><td>';
                                              $date = new \DateTime($login->date);
                                              echo $date->format('F j, Y g:i A');
                                              echo '</td><td>';
                                              echo $login->ipAddress;
                                              echo '</td></tr>';
                                            }
                                          }
                                      ?>
                                      </tbody>
                                    </table>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                <!-- /.portlet-body -->
            </div>
            <!-- /.portlet -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
</div>

<?php 
if(!isset($verifymsg) ) {
  echo '<script type="text/javascript">
      
          $(document).ready(function(){
            $("#messagewager").html("Please go to your email to verify your account. "+
            "And go to profile to change your username. And add you console username.");
            $("#messageWager").popup("show");
  
          });
        </script>';
}
?>

<script type="text/javascript">
$(document).ready(function(){
    
    
  <?php
    foreach($this->tab_show as $tab){
        echo '$(\'a[href="#' . $tab . '"]\').tab(\'show\');';
    }
  ?>
  $('#logins-table').dataTable({"bFilter": false});
});


//
//    function verifyemail(verified) {
//        if(verified) {
//            $("#messagewager").html("Please go to your email to verify your account. "+
//                    "And go to profile to change your username.");
//            $("#messageWager").popup("show");
//        }
//    }
</script>