<?php
    $this->headLink()->appendStylesheet($this->basepath() . '/css/modules/login/login.css');
    $this->headLink()->appendStylesheet($this->basepath() . '/css/demo/index/demo.css');
?>


<!-- login/index/index Begin-->
<div class="mobile_menu row">
  <!--<div class="col-sm-12 mobile_menu_item" data-toggle="modal" data-target="#whatIs">What is the Wager Wall?</div>
  <div class="col-sm-12 mobile_menu_item" data-toggle="modal" data-target="#howDoes">How does it work?</div>
  <div class="col-sm-12 mobile_menu_item" data-toggle="modal" data-target="#betting101">Betting 101</div>
  <div class="col-sm-12 mobile_menu_item" data-toggle="modal" data-target="#faq">FAQ's</div>
  <div class="col-sm-12 mobile_menu_item" data-toggle="modal" data-target="#disclaimer">Disclaimer</div>-->
</div>
<div class="row full_page">
    <div class="col-sm-4 col-md-3 col-lg-2 nav-sidebar-home">
        <div class="row home_left_nav_float"></div>
        <div class="row home_left_nav">
            <div class="row home_left_nav_element">
                <div class="home_left_nav_logo_holder"><img class="home_logo" src="<?php echo $this->basepath();?>/images/login/wagerwall_logo.png"/></div>
            </div>
            <div class="row home_left_nav_element" data-toggle="modal" data-target="#whatisthewagerwall">What is the Wager Wall?</div>
            <div class="row home_left_nav_element" data-toggle="modal" data-target="#howitworks">How does it work?</div>
            <div id="pusher" class="row home_left_nav_element" data-toggle="modal" data-target="#challenge">Create A Wager</div> <!-- Challenge-->
            <!--<div class="row home_left_nav_element" data-toggle="modal" data-target="#betting101">Betting 101</div>-->
           <!--  <div class="row home_left_nav_element" data-toggle="modal" data-target="#faq">FAQ's</div> -->
            <div class="row home_bottom_nav_element" data-toggle="modal" data-target="#termsofuse">
            Terms of Use</div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-8 col-sm-offset-4 col-md-9 col-md-offset-3 col-lg-10 col-lg-offset-2">
        <div class="row home_content_background">
            <div class="col-xs-12 col-sm-offset-4 col-sm-8 col-md-offset-3 col-md-9 col-lg-offset-6 col-lg-6 nav_position_holder_allow_click_events nav_position_holder">
              <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                  <div class="row">
                    <div class="col-md-3 col-sm-4">
                      <a class="home_page_upper_right_button home_login_button btn btn-lg login_open" href="#login">Log in</a>
                    </div>
                    <div class="col-md-3 col-sm-4">
                            <button class="btn btn-lg home_signup_button home_page_upper_right_button" id="open_new_account">Join</button>
                    </div>
                    <div class="col-md-3 col-sm-4">
                      <a class="home_page_upper_right_button home_open_button btn btn-lg postWager_open" id="landingPageWager">CREATE WAGER</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <?php
            /*
             * 
             * First Tab:
             * 
             * 
            */
            ?>
            <div class="col-xs-12" id="homeContentScroll">
                <div class="row content_section home-tab-1">
                    <div class="col-xs-12">
                        <div class="row home_text_content">
<!--                             <div class="wager_board">
                                <?php
                                  if($this->activeWagers) echo $this->partial('back-office/partial/sort_wagers.phtml', 'back-office');
                                  echo $this->partial('back-office/partial/active_wagers.phtml', array('module' => 'back-office', 'wagers' => $this->activeWagers, 'wallet' => \Application\Models\Wallets\AbstractWallet::wagerwallFactory()));
                                ?>
                            </div> -->
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="welcomeToBeta"><h1>Welcome to The Wager Wall beta 1.0</h1></div>
<!-- login/partial/login.phtml Begin-->
<div id="login">
  <?php echo $this->partial('login/partial/login.phtml');?>
</div>
<!-- login/partial/login.phtml End-->
<!-- login/partial/newuser.phtml Begin-->
<div id="newUser">
  <?php echo $this->partial('login/partial/newuser.phtml');?>
</div>
<!-- login/partial/newuser.phtml End-->
<!-- login/partial/forgot_password.phtml Begin-->
<div id="forgotPassword">
    <?php echo $this->partial('login/partial/forgot_password.phtml')?>
</div>
<!-- login/partial/forgot_password.phtml End-->
<div id="forgotSent">
    <div class="row login_popup_box">
        <div class="col-md-12">
            <div class="portlet portlet-black">
                <div class="portlet-heading login-heading">
                    <div class="portlet-title">
                        <h4><strong>Password Reminder</strong>
                        </h4>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="portlet-body">
                    <p>An email has been sent with a link to reset your password.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Terms of use pop up -->
<div class="modal modal-flex fade" id="termsofuse">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="challenge-form-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="whatIsLabel">Terms Of Use</h4>
      </div>
      <div class="modal-body">
        <p>
          These terms and conditions govern your use of this website; by using this website, you accept these terms and conditions in full. If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website. You must be at least 18 years of age to use this website. By using this website you warrant and represent that you are at least 18 years of age. This website uses cookies. By using this website and agreeing to these terms and conditions, you consent to our The WagerWall LLC's use of cookies in accordance with the terms of The WagerWall LLC's privacy policy.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- What is the wager wall popup -->
<div class="modal modal-flex fade" id="whatisthewagerwall">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="challenge-form-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="whatIsLabel">What is the Wager Wall?</h4>
      </div>
      <div class="modal-body">
        <p>
          We allow e-sports players to “Put Their Money Where Their Mouth Is”.  If you crave competition and think you can take on the best, you come to The Wagerwall.  We feature 1v1 wagers in your favorite sports and e-sports games.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- How it works pop up -->
<div class="modal modal-flex fade" id="howitworks">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="challenge-form-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="whatIsLabel">How Does It Work?</h4>
      </div>
      <div class="modal-body">
        <p>
          You have two choices.  You can challenge another player directly or post an “Open” Wager for anyone to take.  The players meet in an agreed upon online location and play their game.  They report the match results, and the funds are distributed.
        </p>
      </div>
    </div>
  </div>
</div>
<!-- Challenge -->
<div class="modal modal-flex fade" id="challenge" tabindex="-1" role="dialog" aria-labelledby="challengeLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="challenge-form-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="whatIsLabel">Create Wager</h4>
      </div>
      <div class="modal-body">
<form>
    <div class = "challenge-form">
      <div class="wagerInputOptionsContainer">
        <input type="radio" name="gender" value="male">   User Wager &nbsp;&nbsp;&nbsp;
      </div>
      <div class="wagerInputOptionsContainer">
        <input type="radio" name="gender" value="female">   Open Wager
      </div>
      <p>Opponent</p>
      <input type="text" name="lastname" placeholder="User"><br>
      <p>Wager Amount (USD)</p>
      <input type="text" name="wagerAmount" placeholder="$0.00"><br>
      <table style="width:100%">
      <tr>
        <td>Console</td>
        <td>Game</td> 
      </tr>
      <tr>
        <td>
            <select>
              <option value="XBOX">XBOX</option>
              <option value="PC">PC</option>
              <option value="Wii">Wii</option>
              <option value="PlayStation">PlayStation</option>
            </select>
        </td>
        <td>
            <select>
              <option value="FIFA">FIFA16</option>
              <option value="Madden16">Madden</option>
              <option value="2k16">NBA 2k16</option>
              <option value="RocketLeagues">RocketLeagues</option>
            </select>
          </td> 
      </tr>
    </table>
  <div>
</form>
      </div>
      <div class="challenge-form-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Create Wager</button>
      </div>
    </div>
  </div>
</div>
<!-- Challenge End -->
<div class="modal modal-flex fade" id="whatIs" tabindex="-1" role="dialog" aria-labelledby="whatIsLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="whatIsLabel">What is the Wager Wall?</h4>
      </div>
      <div class="modal-body">
        <p>The Wager Wall is the world’s first peer-to-peer (P2P) betting site.  Through betting peer-to-peer the standard 
        10% charged by a traditional bookkeeper can be circumvented allowing bettors to keep more money in their pockets when 
        the game doesn’t go their way.  This is a site created of the bettors, by the bettors, for the bettors!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-flex fade" id="howDoes" tabindex="-1" role="dialog" aria-labelledby="howDoesLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="howDoesLabel">How does it work?</h4>
      </div>
      <div class="modal-body">
        <p>The concept is simple: If you think a particular team will win the game, you create a ticket and post a bet on The Wager Wall.
        If another user sees that posted bet and thinks the opponent will win, they can take your bet.   I.e. if you think Dallas will 
        win by 7 points over New England, you fill out a ticket and post it on the Wall for the world to see.  If a New England fan wants 
        to take NE +7, they can take your bet off the wall and they now have some skin in the game. Think Craigslist for Bettors.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-flex fade" id="betting101" tabindex="-1" role="dialog" aria-labelledby="betting101Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="betting101Label">Betting 101</h4>
      </div>
      <div class="modal-body">
        <h4>TYPES OF SPORTS WAGERS (CURRENTLY) AVAILABLE ON THE WAGER WALL</h4>
        <p><b>POINTSPREAD: </b>The most popular sports bets are based on the pointspread. The pointspread represents the margin 
        of points in which the favored team must win by to “cover the spread.” Bets on the pointspread are usually offered at
        11 to 10 odds.  For example, a player must bet $11 to win $10 for a total payout of $21 or $110 to win $100.</p>
        <p><b>MONEY LINE:</b> The money line represents the odds of a team winning the game outright without the use of
        the pointspread. The money line is expressed as a 3-digit number. For example -150 means a player must bet $150 for
        every $100 he wishes to win, $15 for every $10 and multiples thereof.</p>
        <p><b>TOTALS:</b> The combined amount of runs, points or goals scored by both teams during the game, including overtime.
        <br/>---Over– A sports bet in which the player wagers that the combined point total of two teams will be more than
        a specified total.
        <br/>---Under – The player bets that the total points scored by two teams will be less than a certain figure.</p>
        <h4>GLOSSARY OF SPORTS BETTING TERMS</h4>
        <p><b>Action</b> – A sports wager of any kind; a bet.</p>
        <p><b>Added Game</b> – A game not part of the typical menu of wagering offerings, often posted as an accommodation to patrons.</p>
        <p><b>Chalk</b> – The favorite.</p>
        <p><b>Cover</b> – Winning by more than the pointspread.</p>
        <p><b>Dime</b> – A $1,000 sports wager.</p>
        <p><b>Dog</b> – The team perceived to be most likely to lose. Short for underdog.</p>
        <p><b>Favorite</b> – The team considered most likely to win an event.</p>
        <p><b>First-half bet</b> – A bet placed on the score in the  first half of the game only.</p>
        <p><b>Future</b> – Odds that are posted well in advance on the winner of major events, including the Pro Football
        Championship, the Pro Basketball Championship and the Pro Baseball Championship.</p>
        <p><b>Half-time bet</b> – A bet placed on scoring in the second half of a game only.</p>
        <p><b>Handle</b> - The total amount of bets taken.</p>
        <p><b>Laying the points/price</b> – Betting the favorite by giving up points.</p>
        <p><b>Line</b> – The current odds or pointspread on a particular event.</p>
        <p><b>Listed pitchers</b> – A baseball bet placed only if both of the pitchers scheduled to start a game 
        actually start. If they don’t, the bet is deemed “No Action” and refunded.</p>
        <p><b>Longshot</b> – A team perceived to be unlikely to win.</p>
        <p><b>Middle</b> – To win both sides of a game; wagering on the underdog at one pointspread and the favorite at 
        a different pointspread and winning both sides. For example, if the player bets the underdog +4 ½ and the favorite -3 ½ 
        and the favorite wins by 4, he has middled the book and won both bets.</p>
        <p><b>Money line</b> - Odds expressed in terms of money. With money odds, whenever there is a minus (-) the player 
        lays that amount to win $100; where there is a plus (+) the player wins that amount for every $100 wagered.</p>
        <p><b>Nickel</b> – A $500 sports wager.</p>
        <p><b>No action</b> – A wager in which no money is lost or won and the original bet amount is refunded.</p>
        <p><b>Opening line</b> - The earliest line posted for a particular sporting event.</p>
        <p><b>Parlay</b> – A single bet that links together two or more wagers; to win the bet, the player must win all the
        wagers in the parlay. If the player loses one wager, he loses the entire bet.  However, if he wins all the wagers in
        the parlay, he wins a higher payoff than if he had placed the bets separately.</p>
        <p><b>Pick or Pick ‘em</b> – A game when neither team is favored</p>
        <p><b>Price</b> – The odds or pointspread.</p>
        <p><b>Prop (Proposition) Bet</b> – A bet that focuses on the outcome of events within a given game. Props are often
        offered on marquee games of great interest. These include Sunday and Monday night pro football games, various
        high-profile college football games, major college bowl games and playoff and championship games. An example of a
        prop bet is “Which team will score the first touchdown?”</p>
        <p><b>Push</b> – When the contest ends with no winner or loser for wagering purposes; a tie for wagering purposes.</p>
        <p><b>Round Robin</b> – A series of parlays.</p>
        <p><b>Run line</b> – In baseball, a spread used instead of the money line.</p>
        <p><b>Sides</b> – The two teams playing; the underdog and the favorite.</p>
        <p><b>Straight bet</b> – An individual wager on a game or event that will be determined by a pointspread or money line</p>
        <p><b>Straight-up</b> – Winning the game without any regard to the pointspread; a money-line bet.</p>
        <p><b>Take the points</b> – Betting the underdog and receiving its advantage in the pointspread.</p>
        <p><b>Take the price</b> – Betting the underdog and accepting money odds.</p>
        <p><b>Teaser</b> – A type of parlay in which the pointspread or total of each individual play is adjusted. The price of
        moving the pointspread (teasing) is lower payoff odds on winning wagers.</p>
        <p><b>Tie</b> – A wager in which no money is lost or won because the teams’ scores were equal to the number of points 
        in the given pointspread.</p>
        <p><b>Underdog</b> – The team perceived to be most likely to lose. Also known as the “dog.”</p>
        <p><b>Vigorish</b> - The bookmaker’s commission; also known as juice.  (****FLAT $1.00 IN Btc everytime****)</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-flex fade" id="faq" tabindex="-1" role="dialog" aria-labelledby="faqLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="faqLabel">FAQ's</h4>
      </div>
      <div class="modal-body">
        <p><b>1. Why Bitcoin?</b><br/>
        We chose Bitcoin to enable bettors from all parts of the world to get in on the action. Through bitcoin, a bettor in
        Melbourne, Australia can seamlessly post a bet on a European Soccer Match and have it be taken by a bettor in Oslo, Norway.</p>
        <p>
        <p><b>2. What is Bitcoin?</b><br/>
        This video does a much better job than we can of describing it. Check it out here: 
        <a href="https://www.youtube.com/watch?v=Um63OQz3bjo" target="_blank">https://www.youtube.com/watch?v=Um63OQz3bjo</a></p>
        <p><b>3. Will more sports ever be listed on The Wager Wall?</b><br/>
        With your help, Yes!   We started with the most popular sports but will add as many as possible
        once we get traffic on the site.  When logged in you will always have the ability to message us
        here at The Wager Wall office and request another sport be listed.</p>
        <p><b>3. Will I be able to bet on things other than sports?</b><br/>
        Yes again. We plan on adding entertainment, politics, and any category the masses request.</p>
        <p><b>4. If I post a bet and no one picks it up, will I be refunded?</b><br/>
        Yes, once the game has started if your bet was not picked off the wall, you will be refunded instantly.</p>
        <p><b>5. How much do you charge for your service?</b><br/>
        To create a ticket and post on the wall is free. We charge the equivalent of USD$1.00 in Bitcoin to both the bettor and bettee
        once the bet is completed. The purpose of this site is not to make money off the bettors but rather to SAVE money for the 
        (not so lucky) bettors.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-flex fade" id="disclaimer" tabindex="-1" role="dialog" aria-labelledby="disclaimerLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="disclaimerLabel">Disclaimer</h4>
      </div>
      <div class="modal-body">
       <p>The Wager Wall does not promote or encourage illegal or underage gambling, or gambling to persons who reside in jurisdictions where 
       gambling is considered unlawful. In those instances, this site is presented for informational and entertainment purposes only. By 
       entering The Wager Wall you agree that you are aware of the terms outlined herein and reside in an area where it is not unlawful to 
       gamble online.  Please be advised that laws related to betting are different in various jurisdictions.  It is up to the individual 
       looking to participate in online betting to fully research laws related to betting wherever they are.  That also means researching 
       information outside of this Web site.   You shall indemnify and hold harmless any and all owners, directors, officers, managers, 
       employees, agents, partners, vendors, and/or affiliates against any and all harm and damages suffered as a result of using this site.  
       TheWagerWall.com does not accept any responsibility and/or liability for any losses and/or damages sustained by anyone using services 
       linked on this site or following the information provided on the site or via e-mail correspondence.</p>
       <p>WARNING: Betting can be very risky and users should only speculate with money that they can comfortably afford to lose and should
       ensure that the risks involved are fully understood, seeking advice if necessary.  Careless gambling can result in the loss of 
       substantial sums of money. For further information on responsible gambling, or if you think you may have a gambling problem, please 
       <a href="http://www.bettorsanonymous.org" target="_blank">click here.</a></p>
       <p>For questions about TheWagerWall, please contact info@thewagerwall.com</p>
       <p>If you have a questions regarding your account or recent play, please contact Customer Service at info@thewagerwall.com</p>
       <p>TheWagerWall, TheWagerWall logo and all related marks are trademarks.  All rights reserved.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
  $(document).ready(function(){
	  resizeSections();
  });

  $(window).resize(function(){
	  resizeSections();
  });

  function resizeSections(){
	  var windowHeight = $(window).height();
	  $('.content_section').each(function(index){
		  if(windowHeight > $(this).height()){
			  $(this).height(windowHeight);
		  }
	  });
  }

  $.backstretch([
      "<?php echo $this->basepath();?>/images/login/wagerWallController.jpg"
    // , "<?php echo $this->basepath();?>/images/login/hockey.jpg"
    // , "<?php echo $this->basepath();?>/images/login/baseball.jpg"
    // , "<?php echo $this->basepath();?>/images/login/football.jpg"
    // , "<?php echo $this->basepath();?>/images/login/basketball.jpg"
    // , "<?php echo $this->basepath();?>/images/login/soccer.jpg"
    ],
  {duration: 10000, fade: 750});

  
  function scrollToAnchor(anchorId){
    var body = $("html, body");
    body.animate({scrollTop: $('.home-tab-' + anchorId).offset().top},'slow');
  }

  $(document).ready(function(){
    $('#login').popup({
      transition: 'ease-in-out 0.3s',
      vertical: 'top'
    });

    $('#forgotPassword').popup({
      transition: 'ease-in-out 0.3s',
      vertical: 'top'
    });

    $('#forgotSent').popup({
      transition: 'ease-in-out 0.3s',
      vertical: 'top'
    });

    $('#newUser').popup({
      transition: 'ease-in-out 0.3s',
      vertical: 'top'
    });
    
    $('#landingPageWager').click(function(){
      $('#login').popup('hide');
      $('#newUser').popup('show');
    });

    $('#open_new_account').click(function(){
      $('#login').popup('hide');
      $('#newUser').popup('show');
    });

    $('#open_new_account_forgot').click(function(){
      $('#forgotPassword').popup('hide');
      $('#newUser').popup('show');
    });

    $('#forgot_password').click(function(){
      $('#login').popup('hide');
      $('#forgotPassword').popup('show');
    });

    $('#exit_forgot').click(function(){
    	$('#forgotPassword').popup("hide");
    });

    $('#exit_newuser').click(function(){
    	$('#newUser').popup("hide");
    });

    $('#exit_login').click(function(){
    	$('#login').popup("hide");
    });
  });
</script>

<?php 
if(isset($failedLogin) && $failedLogin){
  echo '<script type="text/javascript">
          $(document).ready(function(){
            $("#login").popup("show");
          });
        </script>';
}
if(isset($failedCreate) && $failedCreate){
  echo '<script type="text/javascript">
          $(document).ready(function(){
            $("#newUser").popup("show");
          });
        </script>';
}
if(isset($failedRemind) && $failedRemind){
  echo '<script type="text/javascript">
          $(document).ready(function(){
            $("#forgotPassword").popup("show");
          });
        </script>';
}
if(isset($successRemind) && $successRemind){
  echo '<script type="text/javascript">
          $(document).ready(function(){
            $("#forgotSent").popup("show");
          });
        </script>';
}
?>

<!-- login/index/index End-->