<?php echo $this->partial('login/partial/top_menu.phtml');?>

<!-- begin MAIN PAGE CONTENT -->
<div id="page-wrapper">
    <div class="page-content">
        <div class="row authentication_box_row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-lg-4 col-lg-offset-4">
                <div class="portlet portlet-black">
                    <div class="portlet-heading login-heading">
                        <div class="portlet-title">
                            <h4><strong>Reset your password</strong></h4>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="portlet-body">
<?php 
    if(isset($resetPassword)):
    $resetPassword->setAttribute('action', $this->url('login', array('action' => 'resetpassword', 'controller' => 'index')));
    $resetPassword->prepare();
?>
<?php  echo $this->form()->openTag($resetPassword);?>
    <fieldset>
        <div class="form-group">
            <?php echo $this->formElement($resetPassword->get('password'));?>
            <?php echo $this->formelementerrors($resetPassword->get('password'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($resetPassword->get('repeat_password'));?>
            <?php echo $this->formelementerrors($resetPassword->get('repeat_password'));?>
        </div>
        <input type="hidden" name="token" value="<?php echo $token;?>"/>
        <?php echo $this->formElement($resetPassword->get('submit'));?>
    </fieldset>
<?php  echo $this->form()->closeTag();?>
<?php 
    elseif(isset($error)):
?>
    <p><?php echo $error;?></p>
<?php 
    endif;
?>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.page-content -->
</div>
<!-- /#page-wrapper -->
<!-- end MAIN PAGE CONTENT -->