<?php echo $this->partial('wager/partials/topmenu.phtml');?>
<?php echo $this->partial('wager/partials/sidemenu.phtml');?>
<?php echo $this->partial('wager/partials/talkwall.phtml');?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/backoffice/index.css');?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/wager/mywager.css');?>
 

<?php echo $this->partial('wager/partials/wager.phtml',  array('newwager' => $newwager,'matchresult'=>$matchresult))?>

<!-- begin MAIN PAGE CONTENT -->
<div id="page-wrapper">

    <div class="page-content col-xs-12 col-sm-9 col-md-9">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-title">
                    <h1>Wager History
                    <small>View your recent wagers:</small>
                    </h1>
                    <!-- <ol class="breadcrumb">
                        <li><i class="fa fa-desktop"></i> <a href="<?php echo $this->url('wager', array('action'=>'index', 'controller' => 'index'))?>">The Wager Wall</a></i>
                    </ol> -->
                </div>
            </div>
        </div>
        <div class="pageView" style="display:none;">wagerHistoryView</div>
        <div class="row col-xs-12 col-sm-12 col-md-12">
            <ul class="nav nav-pills pendingWagersNavPills">
              <li id="wagerHistory-All" class="activePill">All</li> 
              <li id="wagerHistory-Wins">Wins</li> 
              <li id="wagerHistory-Losses">Losses</li> 
            </ul>
        </div>
         
        <div class="row wager_wall_font_correct">
            <div class="col-lg-12 padWagerTable">
                <div id = "pageOn" style="display:none;">history</div>
                <ul  id="wagerHistoryList" class="list-group scrollFeature">
                  <?php foreach($this->myWagers as $wager):?>
                   <li class="list-group-item" id="listEvtMatch<?php echo $wager['id'];?>" ur="<?php echo $wager['userAskId'];?>"  wagerid="<?php echo $wager['id'];?>">
                       <div> 
                            <div>
                                <h3><?php echo $wager['consoleName'] . ' - ' . $wager['gameName'] . ' - $'. $wager['riskAmount'];?></h3>
                            </div>
                            <?php if($wager['status'] == 5):?>
                                <?php if($this->userId == $wager['userAskId']):?>
                                    <?php if($wager['askResult'] == 2):?>
                                        <div>Status:<small>I lost against <?php echo $wager['acceptusername'];?></small></div>
                                        <div class="historyStatus" style="display:none;">2</div>
                                    <?php else:?>
                                        <div>Status:<small>I won against <?php echo $wager['acceptusername'];?></small></div>
                                        <div class="historyStatus" style="display:none;">1</div>

                                    <?php endif;?>
                                <?php else:?>
                                    <?php if($wager['acceptResult'] == 2):?>
                                        <div>Status:<small>I lost against <?php echo $wager['askusername'];?></small></div>
                                    <?php else:?>
                                        <div>Status:<small>I won against <?php echo $wager['askusername'];?></small></div>
                                    <?php endif;?>
                                <?php endif;?>
                            <?php endif;?>
                                    
                            <?php if($this->userId == $wager['userAskId']):?>
                                <?php if($wager['status'] == 3):?>
                                    <div>Status:<small><?php echo $wager['acceptusername'];?> - have Declined the Wager</small></div>
                                <?php endif;?>
                                <?php if($wager['status'] == 4):?>
                                    <div>Status:<small>You have Canceled the Wager</small></div>
                                <?php endif;?>
                            <?php else:?>
                                <?php if($wager['status'] == 3):?>
                                    <div>Status:<small>You have Declined the Wager</small></div>
                                <?php endif;?>
                                <?php if($wager['status'] == 4):?>
                                    <div>Status:<small><?php echo $wager['askusername'];?> -  have Canceled the Wager</small></div>
                                <?php endif;?>                                 
                           <?php endif;?>

                            <?php if($wager['status'] == 6):?>
                                <div>Status:<small>Match completed with a truce.</small></div>
                            <?php endif;?>
                            <?php if($wager['status'] == 7):?>
                                <div>Status:<small> Match completed with a dispute.</small></div>
                            <?php endif;?> 
                            <?php if($wager['status'] == 9):?>
                                <?php if($this->userId == $wager['userAskId']):?>
                                    <?php if($wager['askResult'] != 4):?>
                                        <?php if($wager['askResult'] == 6):?>
                                            <div>Status: Match timer expired. <small>I lost against <?php echo $wager['acceptusername'];?></small></div>
                                        <?php else:?>
                                            <div>Status: Match timer expired. <small>I won against <?php echo $wager['acceptusername'];?></small></div>
                                        <?php endif;?> 
                                    <?php else:?>
                                            <div>Status: Match timer expired. <small>Against <?php echo $wager['acceptusername'];?></small></div>
                                    <?php endif;?>    
                                <?php else:?>
                                    <?php if($wager['askResult'] != 4):?>        
                                        <?php if($wager['acceptResult'] == 6):?>
                                            <div>Status: Match timer expired. <small>I lost against <?php echo $wager['askusername'];?></small></div>
                                        <?php else:?>
                                            <div>Status: Match timer expired. <small>I won against <?php echo $wager['askusername'];?></small></div>
                                        <?php endif;?>
                                    <?php else:?>
                                            <div>Status: Match timer expired. <small>Against <?php echo $wager['askusername'];?></small></div>
                                    <?php endif;?>    
                                <?php endif;?>                                        
                            <?php endif;?>                                 
                        </div>
                  </li>
                  <?php endforeach;?>
                </ul>
            </div>
          <div class="clearfix"></div>
        </div>
    </div>
    <!-- /.page-content -->

</div>
<script>
//$(document).ready(function(){
  //  $('#exit_wager').click(function(){
    //  $('#postWager').popup("hide");
   // });
 // });
</script>
<!-- /#page-wrapper -->
<!-- end MAIN PAGE CONTENT -->





