<?php
  $forgot->setAttribute('action', $this->url('login', array('action'=>'index')));
  $forgot->prepare();
?>

<div class="row login_popup_box">
    <div class="col-md-12">
        <div class="exit_x" id="exit_forgot">X</div>
        <div class="portlet portlet-black">
            <div class="portlet-heading login-heading">
                <div class="portlet-title">
                    <h4><strong>Reset your password</strong>
                    </h4>
                </div>
                <div class="portlet-widgets">
                    <button class="btn btn-white btn-xs" id="open_new_account_forgot"><i class="fa fa-plus-circle"></i> Open a New Account</button>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="portlet-body">
                 <?php  echo $this->form()->openTag($forgot);?>
                    <fieldset>
                        <div class="form-group">
                            <?php echo $this->formElement($forgot->get('email'));?>
                            <?php echo $this->formelementerrors($forgot->get('email'));?>
                        </div>
                        <input type="hidden" name="form_type" value="forgot"/>
                        <br>
                        <?php echo $this->formElement($forgot->get('submit'));?>
                    </fieldset>
                 <?php echo $this->form()->closeTag();?>
            </div>
        </div>
    </div>
</div>