<div class="homepageWagerList row">
            <div class="col-lg-12 homepageWagersContainer">
              <h1>The Wager Wall <small> Open Wagers</small></h1>
                <ul id = "wagerList" class="list-group homepageScroll">
                   <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                  <li class="list-group-item">
                       <div> 
                            <div><h3>PC - NBA Live 16 - $35.00</h3></div>
                            <div>User: cashFLO<small> have made an Open Wager</small></div>
                        </div>
                        <div class="individualWager">   
                          <div class="btn-group-vertical" role="group" aria-label="...">     
                              <a id = "acceptmatch" type="button" class="btn btn-success acceptWager_open" href="#acceptWager">Accept</a>
                          </div>
                        </div>                     
                  </li>
                </ul>
            </div>
            <div class="clearfix"></div>
</div>