<div id="homeTalkWallDisplay">
	<h2>TalkWall</h2>
	<select>
		<option>FIFA16 Channel</option>
		<option>Madden Channel</option>
		<option>NBA 2k16 Channel</option>
	</select>

	<ul class="talkWallMessages talkWallScroll">
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li><li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li><li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li><li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
		<li>
			<div class="talkWallMessage">
				<p class="talkWallUser">user101</p>
				<p>lets play</p>
			</div>
			<div class="talkWallMessageTime">
				<p>5:15pm</p>
			</div>
		</li>
	</ul>
	<div class="tagMsgHereContainer">
		<input class="talkWallTextInput" type="textarea" placeholder="tag your message...">
		<button class="btn btn-success btn-md tagSubmitBtn">Tag!</button>
	</div>
</div>
