<!-- begin TOP NAVIGATION -->
<nav class="navbar-top" role="navigation">

    <!-- begin BRAND HEADING -->
    <div class="navbar-header">
        <div class="navbar-brand logofont">
            <a href="/"><span class="logo_red">THE</span><span class="logo_white">WAGER</span><span class="logo_red">WALL</span></a>
        </div>
    </div>
    <!-- end BRAND HEADING -->

    <div class="nav-top">

    </div>
    <!-- /.nav-top -->
</nav>
<!-- /.navbar-top -->
<!-- end TOP NAVIGATION -->