<table cellspacing="0" style="width:550px; border: 3px solid #c9c9c9; font-family: Helvetica, Arial, sans-serif;">
    <tr height="120px" width="100%" style="background-color: #000;" background="https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiMusaj9JPOAhUC6CYKHd9IA9MQjRwIBw&url=http%3A%2F%2Fultimatedogtraining.net%2Faffiliates&psig=AFQjCNEGfB6OoCZAOBptUU21TztLps4fhw&ust=1469717980838529">
        <th style="text-align:right; font-size:1.2em; color: #FFFFFF; padding: 10px;">Password Reset</th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 10px;">
            <div style="margin:auto; width:90%;">
                <h1 style="font-weight:400;font-size:1.5em;color:#d72027;">
                    Forgot your password?
                </h1>
                <div style="font-size:.9em;font-weight:200;">
                    <p style="margin:25px 0px">This email is to reset your password for accessing your WagerWall account. If you did not request to have your password 
                        reset, please disregard this email. If you did request a password reset, please click the link below:
                        </p>
                    <p style="margin:25px 0px">
                        <a href="<?php echo $this->resetLink;?>"><?php echo $this->resetLink;?></a>
                    </p>
                    <p style="margin:25px 0px">This link will be active for the next hour, at which point you will be required to request a new link to complete the password reset process.
                    </p>
                    <p style="margin:10px 0px">Best regards,</p>
                    <p style="margin:10px 0px"><i>The WagerWall</i></p>
                </div>
            </div>
        </td>
    </tr>
    <tr style="background-color:#000;">
        <th style="text-align:center; font-size:.75em;font-weight:100;  color: #FFFFFF; padding: 10px;">
            <p><i>Please note you are receiving this because you have requested a password reset for your account at thewagerwall.com</i></p>
        </th>
    </tr>
</table>