<table cellspacing="0" style="width:550px; border: 3px solid #c9c9c9; font-family: Helvetica, Arial, sans-serif;">
    <tr height="120px" width="100%" style="background-color: #000;">
        <th style="text-align:right; font-size:1.2em; color: #FFFFFF; padding: 10px;">Email Authentication</th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 10px;">
            <div style="margin:auto; width:90%;">
                <h1 style="font-weight: 400;font-size:1.5em;color:#d72027;">WELCOME!</h1>
                <div style="font-size:.9em;font-weight:200;">
                    <p style="margin:25px 0px">Thank you for joining The WagerWall, you can now put your money where your mouth is!</p>
                    <p style="margin:25px 0px">The final step in setting up your account is to authenticate your email address by clicking the
                    link below:</p>
                    <p style="margin:25px 0px">
                        <a href="<?php echo $this->authenticateLink;?>"><?php echo $this->authenticateLink;?></a>
                    </p>
                    <p style="margin:25px 0px">This link will be active for the next 24 hours, at which point you will be required to request a new link to
                    authenticate your email address.</p>
                    <p style="margin:10px 0px">Happy Wagering,</p>
                    <p style="margin:10px 0px"><i>The WagerWall</i></p>
                </div>
            </div>
        </td>
    </tr>
     <tr style="background-color: #000;">
        <th style="text-align:center; font-size:.75em;font-weight:100;color: #FFFFFF; padding: 10px;">
            <p><i>Please note you are receiving this because you have signed up
            for an account at thewagerwall.com</i></p>
        </th>
    </tr>
</table>