<?php echo $this->partial('wager/partials/topmenu.phtml');?>
<?php echo $this->partial('wager/partials/sidemenu.phtml');?>
<?php echo $this->partial('wager/partials/talkwall.phtml', array('theChannels' => $theChannels));?>

<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/backoffice/index.css');?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/wager/mywager.css');?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/backoffice/profile.css');?>

<?php echo $this->partial('wager/partials/wager.phtml',  array('newwager' => $newwager))?>

<?php
  $deposit->setAttribute('action', $this->url('wager', array('action' => 'depositpaypal', 'controller' => 'wallet')));
  $deposit->prepare();
  
  $withdrawal->setAttribute('action', $this->url('wager', array('action' => 'withdrawal', 'controller' => 'wallet')));
  $withdrawal->prepare();
?>

<!-- begin MAIN PAGE CONTENT -->
<div id="page-wrapper">

    <div class="page-content">
    <!-- begin PAGE TITLE ROW -->
    <div class="row">
        <div class="col-lg-12">
            <div class="page-title removeLowerPageTitleMargin">
                <h1>
                    Wager Wallet
                    <small>Make deposits and withdraw:</small>
                </h1>
               <!--  <ol class="breadcrumb">
                    <li><i class="fa fa-desktop"></i>  <a href="<?php echo $this->url('wager', array('action'=>'index', 'controller' => 'index'))?>">The Wager Wall</a>
                    </li>
                    <li class="active">Wallet</li>
                </ol> -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- end PAGE TITLE ROW -->
    <div class="pageView" style="display:none;">walletView</div>
    <div class="row wager_wall_font_correct">
        <div class="col-lg-12 padWagerTable">
    
            <di>
                <div>
                    <ul id="userTab" class="nav nav-tabs">
                        <li class="active"><a href="#profile-settings" data-toggle="tab">Deposit</a>
                        </li>
                        <li><a href="#overview" data-toggle="tab">Withdrawal</a>
                        </li>
                    </ul>
                    <div id="userTabContent" class="tab-content">
                        <div class="tab-pane active fade in" id="profile-settings">
                            <div class="row">
                                <div class="col-sm-9">
                                    <div id="userSettingsContent" class="tab-content">
                                    <?php  echo $this->form()->openTag($deposit);?>
                                        <h3>Deposit to Account</h3>
                                          <div class="col-xs-12 col-sm-12 col-md-12 form-group paymentTypeOptionsContainer">

                                              <?php echo html_entity_decode($this->formElement($deposit->get('paytype')));?>
                                              <?php echo $this->formelementerrors($deposit->get('paytype'));?>

                                          </div>
                                          <div class="col-xs-12 col-sm-12 col-md-12 form-group">

                                              <label>Deposit Amount (USD)</label>
                                              <?php echo $this->formElement($deposit->get('deposit'));?>
                                              <?php echo $this->formelementerrors($deposit->get('deposit'), array('class' => 'error_red'));?>

                                          </div>
                                          <div id="ccredit">
                                              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                                                  <label for="cardtype"><?php echo $this->formLabel($deposit->get('cardtype')); ?></label>
                                                  <?php echo $this->formElement($deposit->get('cardtype'));?>
                                                  <?php echo $this->formelementerrors($deposit->get('cardtype'));?>
                                              </div>
                                              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                                                  <label for="cardnumber"><?php echo $this->formLabel($deposit->get('cardnumber')); ?></label>
                                                  <?php echo $this->formElement($deposit->get('cardnumber'));?>
                                                  <?php echo $this->formelementerrors($deposit->get('cardnumber'));?>
                                              </div>
                                              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                                                  <label for="cvv"><?php echo $this->formLabel($deposit->get('cvv')); ?></label>
                                                  <?php echo $this->formElement($deposit->get('cvv'));?>
                                                  <?php echo $this->formelementerrors($deposit->get('cvv'));?>
                                              </div>  
                                              <div class="col-xs-12 col-sm-6 col-md-6 expDateCCcontainer">
                                                <p>Expiration Date</p>
                                                <div class="form-group expDateOptions">
                                                   <!--  <label for="month"><?php echo $this->formLabel($deposit->get('month')); ?></label> -->
                                                    <?php echo $this->formElement($deposit->get('month'));?>
                                                    <?php echo $this->formelementerrors($deposit->get('month'));?>
                                                </div> 
                                                <div class="form-group expDateOptions">
                                                    <!-- <label for="year"><?php echo $this->formLabel($deposit->get('year')); ?></label>
               -->                                      <?php echo $this->formElement($deposit->get('year'));?>
                                                    <?php echo $this->formelementerrors($deposit->get('year'));?>
                                                </div> 
                                              </div>                          
                                          </div>
                                          <div class="col-xs-12 col-sm-12 col-md-12" id="depositBtnContainer">

                                              <?php echo $this->formElement($deposit->get('submit'));?>
                                              <?php echo $this->form()->closeTag();?>

                                          </div>
                                          <div class="col-xs-12 col-sm-12 col-md-12 paypalSecurityContainer">
                                            <!-- PayPal Logo --><table border="0" cellpadding="10" cellspacing="0" align="center"><tr><td align="center"></td></tr><tr><td align="center"><a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/bdg_secured_by_pp_2line.png" border="0" alt="Secured by PayPal"></a></td></tr></table><!-- PayPal Logo -->
                                            <!-- PayPal Logo --><table border="0" cellpadding="10" cellspacing="0" align="center"><tr><td align="center"></td></tr><tr><td align="center"><a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark"></a></td></tr></table><!-- PayPal Logo -->
                                          </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-content tab-pane fade" id="overview">
                          <div class="row">
                                <div class="col-sm-9">
                                    <div id="userSettingsContent" class="tab-content">
                                        <?php  echo $this->form()->openTag($withdrawal);?>
                                            <h3>Withdrawal Amount</h3>
                                              <div class="col-xs-12 col-sm-12 col-md-12 form-group paymentTypeOptionsContainer">

                                                  <?php echo html_entity_decode($this->formElement($withdrawal->get('withtype')));?>
                                                  <?php echo $this->formelementerrors($withdrawal->get('withtype'));?>

                                              </div>
                                              <div class="col-xs-12 col-sm-12 col-md-12 form-group">

                                                  <label>Withdrawal Amount (USD)</label>
                                                  <?php echo $this->formElement($withdrawal->get('withdrawal'));?>
                                                  <?php echo $this->formelementerrors($withdrawal->get('withdrawal'), array('class' => 'error_red'));?>

                                              </div>

                                              <div class="col-xs-12 col-sm-12 col-md-12" id="depositBtnContainer">

                                                  <?php echo $this->formElement($withdrawal->get('submit'));?>
                                                  <?php echo $this->form()->closeTag();?>

                                              </div>
                                              <div class="col-xs-12 col-sm-12 col-md-12 paypalSecurityContainer">
                                                <!-- PayPal Logo --><table border="0" cellpadding="10" cellspacing="0" align="center"><tr><td align="center"></td></tr><tr><td align="center"><a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/bdg_secured_by_pp_2line.png" border="0" alt="Secured by PayPal"></a></td></tr></table><!-- PayPal Logo -->
                                                <!-- PayPal Logo --><table border="0" cellpadding="10" cellspacing="0" align="center"><tr><td align="center"></td></tr><tr><td align="center"><a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark"></a></td></tr></table><!-- PayPal Logo -->
                                              </div>

                                    </div>
                                </div>
                          </div>
                        </div>
                    </div>
                </div>
                <!-- /.portlet-body -->
            </div>
            <!-- /.portlet -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){

});
</script>