<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headTitle("THE GAMERWALL");?>

    <!-- PACE LOAD BAR PLUGIN - This creates the subtle load bar effect at the top of the page. -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/pace/pace.css');?>
    <?php $this->headScript()->prependFile($this->basePath() . '/js/plugins/pace/pace.js')
                             ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                             ->prependFile($this->basePath() . '/js/jquery.min.js')
                             ->appendFile($this->basePath() . '/js/backstretch.js');?>

    <!-- GLOBAL STYLES - Include these on every page. -->
    <?php $this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/bootstrap/css/bootstrap.min.css')
                           ->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                           ->appendStylesheet('https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic')
                           ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800')
                           ->appendStylesheet($this->basePath() . '/css/fonts/receipt.css')
                           ->appendStylesheet($this->basePath() . '/font-awesome-4.3.0/css/font-awesome.min.css')
                           ->appendStylesheet($this->basePath() . '/css/modules/backoffice/index.css');?>
    <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'), 'PREPEND')?>
  
  
    <?php
    //Elements necessary for the post wager functions.
    $this->headLink()->appendStylesheet($this->basepath() . '/css/plugins/ladda/ladda-themeless.min.css')
                     ->appendStylesheet($this->basepath() . '/css/modules/general/postWager.css');
    $this->headScript()->appendFile($this->basepath() . '/js/plugins/ladda/spin.min.js')
                       ->appendFile($this->basepath() . '/js/plugins/ladda/ladda.min.js')
                       ->appendFile($this->basepath() . '/js/modules/backOffice/postWager.js');
    ?>
  
    <!-- THEME STYLES - Include these on every page. -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css')
                           ->appendStylesheet($this->basePath() . '/css/general.css')
                           ->appendStylesheet($this->basePath() . '/css/plugins.css');?>
    
    <!-- FONT STYLES -->
    <?php $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Source+Code+Pro:200');?>
    
    <?php $this->headScript()->appendFile($this->basePath() . '/js/html5shiv.js', 'screen', 'IE9')
                             ->appendFile($this->basePath() . '/js/respond.min.js', 'screen', 'IE9');?>
    <?php 
        echo $this->headLink();
        echo $this->headScript();
    ?>
</head>

<body>

    <div id="no-style-page-wrapper">
      <?php echo $this->content; ?>
    </div>
    <!-- /#wrapper -->
    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-57436904-1', 'auto');
      ga('send', 'pageview');
    </script>
    
    <?php $this->inlineScript()->prependFile($this->basePath() . '/js/plugins/bootstrap/bootstrap.min.js')
                               ->appendFile($this->basePath() . '/js/plugins/slimscroll/jquery.slimscroll.min.js')
                               ->appendFile($this->basePath() . '/js/plugins/popupoverlay/jquery.popupoverlay.js')
                               ->appendFile($this->basePath() . '/js/plugins/popupoverlay/defaults.js')
                               ->appendFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js');?>

    <!-- Logout Notification jQuery -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/plugins/popupoverlay/logout.js')?>
    
    <!-- HISRC Retina Images -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/plugins/hisrc/hisrc.js')?>

    <!-- THEME SCRIPTS -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/flex.js');?>
    
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/backOffice/main.js')?>
    
    <?php echo $this->inlineScript();?>
</body>

</html>