<!DOCTYPE html>
<html lang="en">
<!--  Begin Head Layout-->
<head>

    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headTitle("THE GAMERWALL");?>

    <!-- PACE LOAD BAR PLUGIN - This creates the subtle load bar effect at the top of the page. -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/pace/pace.css');?>
    <?php $this->headScript()->prependFile($this->basePath() . '/js/plugins/pace/pace.js')
                             ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
                             ->prependFile($this->basePath() . '/js/jquery.min.js')
                             ->appendFile($this->basePath() . '/js/backstretch.js')
                             ->appendFile('https://www.paypalobjects.com/js/external/dg.js')
                             ->appendFile('https://cdn.pubnub.com/pubnub-3.7.1.min.js');?>

    <!-- GLOBAL STYLES - Include these on every page. -->
    <?php $this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/bootstrap/css/bootstrap.min.css')
                           ->appendStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                           ->appendStylesheet('https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic')
                           ->appendStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800')
                           ->appendStylesheet($this->basePath() . '/css/fonts/rbno2.css')
                           ->appendStylesheet($this->basePath() . '/css/fonts/led.css')
                           ->appendStylesheet($this->basePath() . '/css/fonts/receipt.css')
                           ->appendStylesheet($this->basePath() . '/font-awesome-4.3.0/css/font-awesome.min.css')
                           ->appendStylesheet($this->basePath() . '/css/modules/backoffice/index.css');?>
    <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'), 'PREPEND')?>
  
  
    <?php
    //Elements necessary for the post wager functions.
    $this->headLink()->appendStylesheet($this->basepath() . '/css/plugins/ladda/ladda-themeless.min.css')
                     ->appendStylesheet($this->basepath() . '/css/modules/general/postWager.css');
    $this->headScript()->appendFile($this->basepath() . '/js/plugins/ladda/spin.min.js')
                       ->appendFile($this->basepath() . '/js/plugins/ladda/ladda.min.js')
                       ->appendFile($this->basepath() . '/js/modules/backOffice/postWager.js')
                       ->appendFile($this->basepath() . '/js/modules/general/wager_wall.js')
                       ->appendFile($this->basepath() . '/js/plugins/datatables/jquery.dataTables.js')
                       ->appendFile($this->basepath() . '/js/plugins/datatables/datatables-bs3.js');
    ?>
  
    <!-- THEME STYLES - Include these on every page. -->
    <?php $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css')
                           ->appendStylesheet($this->basePath() . '/css/general.css')
                           ->appendStylesheet($this->basePath() . '/css/plugins.css');?>
    
    <!-- FONT STYLES -->
    <?php $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Source+Code+Pro:200');?>
    
    <?php $this->headScript()->appendFile($this->basePath() . '/js/html5shiv.js', 'screen', 'IE9')
                             ->appendFile($this->basePath() . '/js/respond.min.js', 'screen', 'IE9');?>
    <?php 
        echo $this->headLink();
        echo $this->headScript();
    ?>
        <!--Pusher  -->
        <script src="https://js.pusher.com/3.1/pusher.min.js"></script>
</head>
<!-- End Head and Begin Body Layout-->
<body>
     <!-- /#Layout wrapper Begin-->
    <div id="wrapper">
      <!-- Layout Content Begin-->
      <?php echo $this->content; ?>
      <!-- Layout Content End-->
      <!-- back-office/wager/partials/post.phtml Begin-->
      <div id="postWagers">
        <?php //echo $this->partial('back-office/wager/partials/post.phtml', 'back-office')?>
        <?php //echo $this->partial('wager/partials/wager.phtml', 'wager')?>
      </div>
      <!-- back-office/wager/partials/post.phtml End-->
      <!-- back-office/wager/partials/take.phtml Begin-->
      <div id="takeWager">
        <?php echo $this->partial('back-office/wager/partials/take.phtml', 'back-office')?>
      </div>
      <!-- back-office/wager/partials/take.phtml End-->
    </div>
    <!-- /#Layout wrapper End-->

    <!-- GLOBAL SCRIPTS -->
    <script type="text/javascript">
      $(document).ready(function(){
         $('#postWager').popup({
          transition: 'ease-in-out 0.3s',
          vertical: 'top'
        });
       $('#madeWager').popup({
          transition: 'ease-in-out 0.3s',
          vertical: 'top'
        });
        $('#takeWager').popup({
          transition: 'ease-in-out 0.3s',
          vertical: 'top'
        });
      });
    </script>
    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-57436904-1', 'auto');
      ga('send', 'pageview');
    </script>
    
    <?php $this->inlineScript()->prependFile($this->basePath() . '/js/plugins/bootstrap/bootstrap.min.js')
                               ->appendFile($this->basePath() . '/js/plugins/slimscroll/jquery.slimscroll.min.js')
                               ->appendFile($this->basePath() . '/js/plugins/popupoverlay/jquery.popupoverlay.js')
                               ->appendFile($this->basePath() . '/js/plugins/popupoverlay/defaults.js')
                               ->appendFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js');?>
    
    <?php echo $this->partial('wager/partials/logout.phtml');?>
    <!-- Logout Notification jQuery -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/plugins/popupoverlay/logout.js')?>
    
    <!-- HISRC Retina Images -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/plugins/hisrc/hisrc.js')?>
       

    <!-- THEME SCRIPTS -->
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/flex.js');?>
    
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/backOffice/main.js')?>
    
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/wager/wager.js')?>
    
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/wager/wallet.js')?> 
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/wager/messages.js')?>
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/wager/general.js')?>
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/modules/wager/talk.js')?>
    
    <?php $this->inlineScript()->appendFile($this->basePath() . '/js/pusher/pushers.js')?>
    
    <!-- inlineScript -->
    <?php echo $this->inlineScript();?>
</body>
<!-- End Body Layout-->
</html>
