<?php echo $this->partial('wager/partials/topmenu.phtml');?>
<?php echo $this->partial('wager/partials/sidemenu.phtml');?>
<?php echo $this->partial('wager/partials/talkwall.phtml');?>

<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/backoffice/index.css');?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/modules/wager/mywager.css');?>
 

<?php echo $this->partial('wager/partials/wager.phtml',  array('newwager' => $newwager,'matchresult'=>$matchresult))?>
<?php echo $this->partial('wager/message/partials/msgpopup.phtml',  array('message' => $message))?>
<!-- begin MAIN PAGE CONTENT -->
<div id="page-wrapper">
	<div class="col-xs-12 col-sm-9 col-md-9 legalInformationContainer legalInformationScroll">

	   <h1><small>The GamerWall LLC Terms and Conditions</small></h1>
		<h3>Introduction</h3>
          <p>
          These terms and conditions govern your use of this website; by using this website, you accept these terms and conditions in full.   If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website. 

You must be at least 18 years of age to use this website.  By using this website you warrant and represent that you are at least 18 years of age.

This website uses cookies.  By using this website and agreeing to these terms and conditions, you consent to our The GamerWall LLC's use of cookies in accordance with the terms of The GamerWall LLC's privacy policy.

          </p>
          <h3>Legal Compliance</h3>
          <p>
         You are subject to, and are solely responsible for obeying all laws of the state, province and/or country in which you reside and from which you access the site, log-in to the site or participate in any head-to-head or tournament skill challenges. You agree to only participate in the skill challenges only after you have determined in good-faith that you are in compliance with state, local and other governing laws and regulations.

         Participation within the United States of America (U.S.)
         Participation in fee-based tournaments for prizes is prohibited in the following U.S. states, without limitation: Alaska, Arizona, Delaware, Iowa, Maryland, Tennessee, Vermont. The foregoing list shall not be construed to imply or suggest that Your participation in Skill Challenges from an unlisted state is legal under any applicable laws or regulations. VOID WHERE PROHIBITED OR RESTRICTED BY LAW.

         Participation outside the U.S.
         Participation in fee-based tournaments for prizes may be prohibited in your jurisdiction and it is your sole responsibility to ensure compliance with such laws. VOID WHERE PROHIBITED OR RESTRICTED BY LAW.


         You agree to hold GamerWall LLC harmless from any liability such that we cannot be held liable if laws applicable to you restrict or prohibit your participation in any skill challenge or contests arranged and established through the site or otherwise. We make no representations or warranties, implicit or explicit, as to Your legal right to participate in any skill challenge facilitated nor shall any person affiliated, or claiming affiliation with GamerWall LLC, have authority to make such representations or warranties.
          </p>
          <h3>License to Use Website</h3>
          <p>
          Unless otherwise stated, The GamerWall LLC and/or its licensors own the intellectual property rights in the website and material on the website.  Subject to the license below, all these intellectual property rights are reserved.
          You may view, download for caching purposes only, and print pages or other content from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms and conditions.  
          </p>
          <p>You must not:</p>
          <ul>
            <li>republish material from this website (including republication on another website);</li>
            <li>sell, rent or sub-license material from the website;</li>
            <li>show any material from the website in public;</li>
            <li>reproduce, duplicate, copy or otherwise exploit material on this website for a commercial purpose;</li>
            <li>edit or otherwise modify any material on the website; or</li>
            <li>redistribute material from this website except for content specifically and expressly made available for redistribution.</li>
            </ul>
            <h3>Acceptable Use</h3>
            <p>
            You must not use this website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.

            You must not use this website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.


            You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this website without The GamerWall LLC’s express written consent.

            You must not use this website to transmit or send unsolicited commercial communications.

            You must not use this website for any purposes related to marketing without The GamerWall LLC’s express written consent.
            </p>
            <h3>Restricted Access</h3>
            <p>
            Access to certain areas of this website is restricted.  The GamerWall LLC reserves the right to restrict access to other areas of this website, or indeed this entire website, at The GamerWall LLC’s discretion.

If The GamerWall LLC provides you with a user ID and password to enable you to access restricted areas of this website or other content or services, you must ensure that the user ID and password are kept confidential.  

The GamerWall LLC may disable your user ID and password in The GamerWall’s sole discretion without notice or explanation.

            </p>
            <h3>User Content</h3>
            <p>
            In these terms and conditions, “your user content” means material (including without limitation text, images, audio material, video material and audio-visual material) that you submit to this website, for whatever purpose.


You grant to The GamerWall LLC a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, adapt, publish, translate and distribute your user content in any existing or future media.  You also grant to The GamerWall LLC the right to sub-license these rights, and the right to bring an action for infringement of these rights.

Your user content must not be illegal or unlawful, must not infringe any third party's legal rights, and must not be capable of giving rise to legal action whether against you or The GamerWall LLC or a third party (in each case under any applicable law).  

You must not submit any user content to the website that is or has ever been the subject of any threatened or actual legal proceedings or other similar complaint.

The GamerWall LLC reserves the right to edit or remove any material submitted to this website, or stored on The GamerWall LLC’s servers, or hosted or published upon this website.

Notwithstanding The GamerWall LLC’s rights under these terms and conditions in relation to user content, The GamerWall LLC does not undertake to monitor the submission of such content to, or the publication of such content on, this website.

            </p>
            <h3>No Warranties</h3>
            <p>

           This website is provided “as is” without any representations or warranties, express or implied.  The GamerWall LLC makes no representations or warranties in relation to this website or the information and materials provided on this website.  
 
        </p>
        <p>
        Without prejudice to the generality of the foregoing paragraph, The GamerWall LLC does not warrant that:
        </p>
        <ul>
          <li>this website will be constantly available, or available at all; or</li>
          <li>the information on this website is complete, true, accurate or non-misleading.</li>
        </ul>
        <p>
       Nothing on this website constitutes, or is meant to constitute, advice of any kind. 

        </p>
        <h3>Limitations of Liability</h3>
            <p>
           

The GamerWall LLC will not be liable to you (whether under the law of contact, the law of torts or otherwise) in relation to the contents of, or use of, or otherwise in connection with, this website:
<ul>
              <li>for any indirect, special or consequential loss; or</li>
              <li>for any business losses, loss of revenue, income, profits or anticipated savings, loss of contracts or business relationships, loss of reputation or goodwill, or loss or corruption of information or data.</li>
            </ul>

            </p>
            <h3>Exceptions</h3>
            <p>

            Nothing in this website disclaimer will exclude or limit any warranty implied by law that it would be unlawful to exclude or limit; and nothing in this website disclaimer will exclude or limit The GamerWall LLC’s liability in respect of any:
            </p>
            <ul>
              <li>death or personal injury caused by The GamerWall LLC’s negligence;</li>
              <li>fraud or fraudulent misrepresentation on the part of The GamerWall LLC; or</li>
              <li>matter which it would be illegal or unlawful for The GamerWall LLC to exclude or limit, or to attempt or purport to exclude or limit, its liability. </li>
            </ul>
            <h3>Reasonableness</h3>
            <p>
          By using this website, you agree that the exclusions and limitations of liability set out in this website disclaimer are reasonable.  

If you do not think they are reasonable, you must not use this website.

            </p>
            <h3>Other Parties</h3>
            <p>

           You accept that, as a limited liability entity, The GamerWall LLC has an interest in limiting the personal liability of its officers and employees.  You agree that you will not bring any claim personally against The GamerWall LLC’s officers or employees in respect of any losses you suffer in connection with the website.

Without prejudice to the foregoing paragraph,] you agree that the limitations of warranties and liability set out in this website disclaimer will protect The GamerWall LLC’s officers, employees, agents, subsidiaries, successors, assigns and sub-contractors as well as The GamerWall LLC. 


            </p>
            <h3>Unenforcable Provisions</h3>
            <p>
            If any provision of this website disclaimer is, or is found to be, unenforceable under applicable law, that will not affect the enforceability of the other provisions of this website disclaimer.
            </p>
            <h3>Indemnity</h3>
            <p>

            You hereby indemnify The GamerWall LLC and undertake to keep The GamerWall LLC indemnified against any losses, damages, costs, liabilities and expenses (including without limitation legal expenses and any amounts paid by The GamerWall LLC to a third party in settlement of a claim or dispute on the advice of The GamerWall LLC’s legal advisers) incurred or suffered by The GamerWall LLC arising out of any breach by you of any provision of these terms and conditions, or arising out of any claim that you have breached any provision of these terms and conditions.

            </p>
            <h3>Breaches of these Terms and Conditions</h3>
            <p>

           Without prejudice to The GamerWall LLC’s other rights under these terms and conditions, if you breach these terms and conditions in any way, The GamerWall LLC may take such action as The GamerWall LLC deems appropriate to deal with the breach, including suspending your access to the website, prohibiting you from accessing the website, blocking computers using your IP address from accessing the website, contacting your internet service provider to request that they block your access to the website and/or bringing court proceedings against you.


            </p>
            <h3>Variation</h3>
            <p>
            The GamerWall LLC may revise these terms and conditions from time-to-time.  Revised terms and conditions will apply to the use of this website from the date of the publication of the revised terms and conditions on this website.  Please check this page regularly to ensure you are familiar with the current version.
            </p>
            <h3>Assignment</h3>
            <p>

            The GamerWall LLC may transfer, sub-contract or otherwise deal with The GamerWall LLC’s rights and/or obligations under these terms and conditions without notifying you or obtaining your consent.

You may not transfer, sub-contract or otherwise deal with your rights and/or obligations under these terms and conditions.   

            </p>
            <h3>Severability</h3>
            <p>
           If a provision of these terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect.  If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect. 

            </p>
            <h3>Entire Agreement</h3>
            <p>

            These terms and conditions, together with our Privacy Policy, constitute the entire agreement between you and The GamerWall LLC in relation to your use of this website, and supersede all previous agreements in respect of your use of this website.
            </p>
            <h3>Legal Jurisdiction</h3>
            <p>

            These terms and conditions will be governed by and construed in accordance with The GamerWall LLC’s local jurisdiction, and any disputes relating to these terms and conditions will be subject to the non-exclusive jurisdiction of the courts of Harris County.
            </p>
            <h3>Contact</h3>
            <p>You can contact The GamerWall LLC by:</p>
            <p>Address: 16518 House Hahl Rd. Cypress, TX 77433</p>
            <p>Phone: 832.474.4981</p>
            <p>Email: support@thegamerwall.com</p>
            <p>Hours of operation: 8-6 CST</p>
   	</div>
    <!-- /.page-content -->
</div>
<!-- /#page-wrapper -->
<!-- end MAIN PAGE CONTENT -->

